# FUNDING.yml

# GitHub Sponsors funding configuration.
# Documented at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [LaurentOngaro]
patreon: LaurentOngaro
ko_fi: LaurentOngaro
tipeee: laurentongaro
custom: ["https://fr.tipeee.com/laurentongaro"]